# Generated by Django 5.0.1 on 2024-12-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_fullname', models.CharField(max_length=30)),
                ('a_login_id', models.CharField(max_length=30, unique=True)),
                ('a_password', models.CharField(max_length=10)),
                ('a_contact', models.BigIntegerField()),
                ('a_email', models.EmailField(max_length=30)),
                ('a_address', models.CharField(max_length=50)),
            ],
        ),
    ]
