# Generated by Django 5.0.1 on 2024-12-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_fullname', models.CharField(max_length=30)),
                ('a_login_id', models.CharField(max_length=30, unique=True)),
                ('a_password', models.CharField(max_length=10)),
                ('a_contact', models.BigIntegerField()),
                ('a_email', models.EmailField(max_length=30)),
                ('a_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_fullname', models.CharField(max_length=30)),
                ('c_login_id', models.CharField(max_length=30, unique=True)),
                ('c_password', models.CharField(max_length=10)),
                ('c_contact', models.BigIntegerField()),
                ('c_email', models.EmailField(max_length=30)),
                ('c_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Electrician',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_fullname', models.CharField(max_length=30)),
                ('e_login_id', models.CharField(max_length=30, unique=True)),
                ('e_password', models.CharField(max_length=10)),
                ('e_contact', models.BigIntegerField()),
                ('e_email', models.EmailField(max_length=30)),
                ('e_address', models.CharField(max_length=50)),
                ('e_qualification', models.CharField(max_length=15)),
            ],
        ),
    ]
