# Generated by Django 5.0.1 on 2024-12-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrician',
            name='e_qualification',
            field=models.CharField(max_length=30),
        ),
    ]
