# Generated by Django 5.0.1 on 2024-12-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_electrician_e_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_address',
            field=models.CharField(max_length=256),
        ),
    ]
