# Generated by Django 5.0.1 on 2024-12-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0003_alter_electrician_e_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('s_description', models.CharField(max_length=30)),
                ('s_price', models.IntegerField()),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.electrician')),
            ],
        ),
    ]
