# Generated by Django 5.0.1 on 2024-12-15 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_electrician_e_qualification'),
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='e_id',
            field=models.ForeignKey(db_column='e_id', on_delete=django.db.models.deletion.CASCADE, to='profile.electrician'),
        ),
    ]
