# Generated by Django 5.0.1 on 2024-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_service_e_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='s_description',
            field=models.CharField(max_length=100),
        ),
    ]
