# Generated by Django 5.0.1 on 2024-12-16 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0003_alter_electrician_e_qualification'),
        ('service_app', '0003_alter_service_s_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_status', models.CharField(max_length=10)),
                ('b_amt', models.IntegerField()),
                ('b_date', models.DateField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.customer')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.service')),
            ],
        ),
    ]
